⚡ Feature - App bar, Back App bar, Back App bar with plus button
GDSC-DGU/2024-SolutionChallenge-EarthAndI pull request #6
Opened 2024-02-04 19:22 UTC by wonho1401

## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #4 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

<img src="https://github.com/GDSC-DGU/2024-SolutionChallenge-EarthAndI/assets/59119468/dd3de1a2-0c59-49ae-8c39-9adbe48030e0" height="500"/>

- Change text position in default app bar 
- Change text position in default back app bar
- Add plus button if user is on the add friend page

2024-02-04 19:26 UTC, HyungJoonSon commented on app/lib/widgets/appbar/default_back_appbar.dart
> +      {super.key, required this.title, required this.isFriendScreen});
bool 값이 아닌 action List를 받아오게 해서 각 화면마다 커스텀할 수 있게 하면 어떨까 싶습니다.

2024-02-04 19:28 UTC, HyungJoonSon commented on app/lib/widgets/appbar/default_back_appbar.dart
> +            },
이 부분에 있어서 centerTile 값을 true로 주고 title을 유지하는게 widget tree의 depth를 줄일 수 있을 거 같습니다.
또한, LeadingWidth을 90으로 유지하고 IconButton을 Leading에 넣어주는 것도 좋을 거 같습니다. 이렇게 한다면 불필요한 Row를 없앨 수 있겠죠??

2024-02-04 19:31 UTC, HyungJoonSon requested changes
Comment 달았습니다! 전반적으로 코드 읽기 좋았습니다!

2024-02-04 19:31 UTC, HyungJoonSon commented on app/lib/widgets/appbar/default_back_appbar.dart
> +      ],
위에서 올렸듯이 밖에서 action을 정의할 수 있다면 좀 더 공통 위젯에 맞을 거 같습니다.

2024-02-04 21:16 UTC, shimseohyun approved these changes
정말 잘 하셨습니다

2024-02-04 21:16 UTC, shimseohyun commented on app/lib/utilities/system/font_system.dart
> +    fontFamily: 'Pretendard',
폰트 스타일 등록할째 높이값도 넣어주시면 감사하겠습니다! Head2(pretendard semibold) 의 경우 height: 24 / 20 를 사용합니다.

Body 폰트의 경우 가독성을 위해서 Head 폰트보다 행간을 넓게 사용하고 있습니다. 피그마 한 번 확인 해주세요^_^

2024-02-05 14:59 UTC, wonho1401 commented on app/lib/utilities/system/font_system.dart
> +    fontFamily: 'Pretendard',
감사합니다~ 수정하겠습니다 :)

2024-02-05 18:12 UTC, HyungJoonSon commented on app/lib/widgets/appbar/default_back_appbar.dart
> +    this.actions = const <CustomIconButton>[],
final을 사용할 때는 보통 required 를 달아주고, 앨비스 연산자(?)를 사용하면 this로 바로 나타냅니다.

2024-02-05 18:13 UTC, HyungJoonSon approved these changes
고생하셨습니다!

2024-02-05 18:20 UTC, wonho1401 commented on app/lib/widgets/appbar/default_back_appbar.dart
> +    this.actions = const <CustomIconButton>[],
좋은 정보 감사합니다~~ :)

2024-02-05 18:50 UTC, shimseohyun approved these changes
정말 잘 하셨어요~

2024-02-05 18:51 UTC, merged